import '@/styles/globals.css';

import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Providers } from '@/providers';
import Navbar from '@/components/commons/navbar';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='h-screen w-screen overflow-x-hidden relative'>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
